@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 05 14:53:50 -0500 2024
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim urbanaman_rom_sim_behav -key {Behavioral:sim_1:Functional:urbanaman_rom_sim} -tclbatch urbanaman_rom_sim.tcl -protoinst "protoinst_files/mb_block_i.protoinst" -log simulate.log"
call xsim  urbanaman_rom_sim_behav -key {Behavioral:sim_1:Functional:urbanaman_rom_sim} -tclbatch urbanaman_rom_sim.tcl -protoinst "protoinst_files/mb_block_i.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
