# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/snesconst.xdc

# XDC: imports/imports/urbana_ddr3.xdc

# IP: ip/blk_mem_gen_vram/blk_mem_gen_vram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_vram || ORIG_REF_NAME==blk_mem_gen_vram} -quiet] -quiet

# IP: ip/blk_mem_gen_aram/blk_mem_gen_aram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_aram || ORIG_REF_NAME==blk_mem_gen_aram} -quiet] -quiet

# IP: ip/blk_mem_brr_buf/blk_mem_brr_buf.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_brr_buf || ORIG_REF_NAME==blk_mem_brr_buf} -quiet] -quiet

# IP: ip/blk_mem_gen_oam/blk_mem_gen_oam.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_oam || ORIG_REF_NAME==blk_mem_gen_oam} -quiet] -quiet

# IP: ip/blk_mem_gen_cgram/blk_mem_gen_cgram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_cgram || ORIG_REF_NAME==blk_mem_gen_cgram} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
