# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/snesconst.xdc

# XDC: imports/urbana_ddr3.xdc

# Block Designs: bd/snes_block/snes_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block || ORIG_REF_NAME==snes_block} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_microblaze_0_1/snes_block_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_microblaze_0_1 || ORIG_REF_NAME==snes_block_microblaze_0_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_xbar_0/snes_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_xbar_0 || ORIG_REF_NAME==snes_block_xbar_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_9/snes_block_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_9 || ORIG_REF_NAME==snes_block_auto_pc_9} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_0/snes_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_0 || ORIG_REF_NAME==snes_block_auto_pc_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_1/snes_block_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_1 || ORIG_REF_NAME==snes_block_auto_pc_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_2/snes_block_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_2 || ORIG_REF_NAME==snes_block_auto_pc_2} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_3/snes_block_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_3 || ORIG_REF_NAME==snes_block_auto_pc_3} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_4/snes_block_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_4 || ORIG_REF_NAME==snes_block_auto_pc_4} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_5/snes_block_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_5 || ORIG_REF_NAME==snes_block_auto_pc_5} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_6/snes_block_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_6 || ORIG_REF_NAME==snes_block_auto_pc_6} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_7/snes_block_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_7 || ORIG_REF_NAME==snes_block_auto_pc_7} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_auto_pc_8/snes_block_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_auto_pc_8 || ORIG_REF_NAME==snes_block_auto_pc_8} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_microblaze_0_axi_periph_1/snes_block_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_microblaze_0_axi_periph_1 || ORIG_REF_NAME==snes_block_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_microblaze_0_axi_intc_1/snes_block_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_microblaze_0_axi_intc_1 || ORIG_REF_NAME==snes_block_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_microblaze_0_xlconcat_0/snes_block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==snes_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_mdm_1_1/snes_block_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_mdm_1_1 || ORIG_REF_NAME==snes_block_mdm_1_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_timer_0_0/snes_block_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_timer_0_0 || ORIG_REF_NAME==snes_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_uartlite_0_0/snes_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_uartlite_0_0 || ORIG_REF_NAME==snes_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_gpio_0_0/snes_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_gpio_0_0 || ORIG_REF_NAME==snes_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_gpio_1_0/snes_block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_gpio_1_0 || ORIG_REF_NAME==snes_block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_gpio_2_0/snes_block_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_gpio_2_0 || ORIG_REF_NAME==snes_block_axi_gpio_2_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_quad_spi_0_0/snes_block_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_quad_spi_0_0 || ORIG_REF_NAME==snes_block_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_dlmb_v10_1/snes_block_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_dlmb_v10_1 || ORIG_REF_NAME==snes_block_dlmb_v10_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_ilmb_v10_1/snes_block_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_ilmb_v10_1 || ORIG_REF_NAME==snes_block_ilmb_v10_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_dlmb_bram_if_cntlr_1/snes_block_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==snes_block_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_ilmb_bram_if_cntlr_1/snes_block_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==snes_block_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_lmb_bram_1/snes_block_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_lmb_bram_1 || ORIG_REF_NAME==snes_block_lmb_bram_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_gpio_0_1/snes_block_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_gpio_0_1 || ORIG_REF_NAME==snes_block_axi_gpio_0_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_axi_gpio_1_1 || ORIG_REF_NAME==snes_block_axi_gpio_1_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_mig_7series_0_1/snes_block_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_mig_7series_0_1 || ORIG_REF_NAME==snes_block_mig_7series_0_1} -quiet] -quiet

# IP: bd/snes_block/ip/snes_block_rst_mig_7series_0_83M_1/snes_block_rst_mig_7series_0_83M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snes_block_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==snes_block_rst_mig_7series_0_83M_1} -quiet] -quiet

# IP: ip/blk_mem_brr_buf/blk_mem_brr_buf.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_brr_buf || ORIG_REF_NAME==blk_mem_brr_buf} -quiet] -quiet

# IP: ip/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/snes_block_ooc.xdc
