# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.runs/synth_1/SNES_toplevel.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Synth 8-7129}  -suppress 
set_msg_config  -id {IP_Flow 19-2248}  -string {{WARNING: [IP_Flow 19-2248] Failed to load user IP repository 'd:/Desktop/hdmi_tx_1.0'; Can't find the specified path.
If this directory should no longer be in your list of user repositories, go to the IP Settings dialog and remove it.}}  -suppress 
set_msg_config  -id {Synth 8-7080}  -string {{WARNING: [Synth 8-7080] Parallel synthesis criteria is not met}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.cache/wt [current_project]
set_property parent.project_path C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/sapph/OneDrive/Desktop/hdmi_tx_1.0
  c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/CX4/drom.mif
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/DSP/dsp11b23410_p.mif
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/BSX/bsx121-124.mif
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/DSP/dsp11b23410_d.mif
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/design_source/VGA_controller.sv
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/design_source/hex_driver.sv
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/V2SV-main/main.sv
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/new/SNES_toplevel.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/new/HOAM.v
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/new/REGRAM.v
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/new/SPR_BUF.v
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/new/WRAM.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/P65816_pkg.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/BCDAdder.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/AddSubBCD.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/ALU.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/SPC700_pkg.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/AddSub.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/BCDAdj.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/ALU.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/AddrGen.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/AddrGen.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/CEGen.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/MCode.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/65C816/P65C816.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/CPU.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/DSP_PKG.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/DSP.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/DSP/OBC1.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/SRTC.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/chip/DSP/DSP_LHRomMap.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/MCode.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/MulDiv.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/PPU_PKG.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/PPU.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SPC700/SPC700.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SMP.vhd
  C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SWRAM.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/imports/rtl/SNES.vhd
add_files C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/bd/snes_block/snes_block.bd
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_1/snes_block_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_1/snes_block_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_1/snes_block_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_xbar_0/snes_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_9/snes_block_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_0/snes_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_1/snes_block_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_2/snes_block_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_3/snes_block_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_4/snes_block_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_5/snes_block_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_6/snes_block_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_7/snes_block_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_auto_pc_8/snes_block_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_axi_intc_1/snes_block_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_axi_intc_1/snes_block_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_axi_intc_1/snes_block_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_mdm_1_1/snes_block_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_mdm_1_1/snes_block_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_timer_0_0/snes_block_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_timer_0_0/snes_block_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_uartlite_0_0/snes_block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_uartlite_0_0/snes_block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_uartlite_0_0/snes_block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_0/snes_block_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_0/snes_block_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_0/snes_block_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_0/snes_block_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_0/snes_block_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_0/snes_block_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_2_0/snes_block_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_2_0/snes_block_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_2_0/snes_block_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_quad_spi_0_0/snes_block_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_quad_spi_0_0/snes_block_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_quad_spi_0_0/snes_block_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_quad_spi_0_0/snes_block_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_dlmb_v10_1/snes_block_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_ilmb_v10_1/snes_block_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_dlmb_bram_if_cntlr_1/snes_block_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_ilmb_bram_if_cntlr_1/snes_block_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_lmb_bram_1/snes_block_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_1/snes_block_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_1/snes_block_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_0_1/snes_block_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_mig_7series_0_1/snes_block_mig_7series_0_1/user_design/constraints/snes_block_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_mig_7series_0_1/snes_block_mig_7series_0_1/user_design/constraints/snes_block_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_rst_mig_7series_0_83M_1/snes_block_rst_mig_7series_0_83M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_rst_mig_7series_0_83M_1/snes_block_rst_mig_7series_0_83M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_rst_mig_7series_0_83M_1/snes_block_rst_mig_7series_0_83M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/snes_block_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_microblaze_0_1/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_brr_buf/blk_mem_brr_buf.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_brr_buf/blk_mem_brr_buf_ooc.xdc]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_aram/blk_mem_gen_aram.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_aram/blk_mem_gen_aram_ooc.xdc]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_vram/blk_mem_gen_vram.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_vram/blk_mem_gen_vram_ooc.xdc]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_cgram/blk_mem_gen_cgram.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_cgram/blk_mem_gen_cgram_ooc.xdc]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam_ooc.xdc]

read_ip -quiet C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/constrs_1/imports/snesconst.xdc
set_property used_in_implementation false [get_files C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/constrs_1/imports/snesconst.xdc]

read_xdc C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/constrs_1/imports/urbana_ddr3.xdc
set_property used_in_implementation false [get_files C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/constrs_1/imports/urbana_ddr3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/utils_1/imports/synth_1/mb_ddr3_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top SNES_toplevel -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SNES_toplevel.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SNES_toplevel_utilization_synth.rpt -pb SNES_toplevel_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
