# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/7provide/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block_i/mb_block_i.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i || ORIG_REF_NAME==mb_block_i} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_microblaze_0_1/mb_block_i_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_1 || ORIG_REF_NAME==mb_block_i_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_dlmb_v10_1/mb_block_i_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_dlmb_v10_1 || ORIG_REF_NAME==mb_block_i_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_ilmb_v10_1/mb_block_i_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_ilmb_v10_1 || ORIG_REF_NAME==mb_block_i_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_dlmb_bram_if_cntlr_1/mb_block_i_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_block_i_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_ilmb_bram_if_cntlr_1/mb_block_i_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_block_i_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_lmb_bram_1/mb_block_i_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_lmb_bram_1 || ORIG_REF_NAME==mb_block_i_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_xbar_1/mb_block_i_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_xbar_1 || ORIG_REF_NAME==mb_block_i_xbar_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_microblaze_0_axi_periph_1/mb_block_i_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_block_i_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_microblaze_0_axi_intc_1/mb_block_i_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_block_i_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_mdm_1_1/mb_block_i_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_mdm_1_1 || ORIG_REF_NAME==mb_block_i_mdm_1_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_clk_wiz_1_1/mb_block_i_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_clk_wiz_1_1 || ORIG_REF_NAME==mb_block_i_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_rst_clk_wiz_1_100M_1/mb_block_i_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_block_i_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_axi_uartlite_0_1/mb_block_i_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_axi_uartlite_0_1 || ORIG_REF_NAME==mb_block_i_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_block_i/ip/mb_block_i_hdmi_text_controller_0_1/mb_block_i_hdmi_text_controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_hdmi_text_controller_0_1 || ORIG_REF_NAME==mb_block_i_hdmi_text_controller_0_1} -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/Lab7/Lab7.gen/sources_1/bd/mb_block_i/mb_block_i_ooc.xdc
