# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xci
# IP: The module: 'snes_block_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.srcs/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xci
# IP: The module: 'snes_block_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/SNESonUrbana/SNESonUrbana.gen/sources_1/bd/snes_block/ip/snes_block_axi_gpio_1_1/snes_block_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'snes_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
