# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/TheSNESRedo/TheSNESRedo.srcs/sources_1/ip/blk_mem_rom/blk_mem_rom.xci
# IP: The module: 'blk_mem_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/TheSNESRedo/TheSNESRedo.gen/sources_1/ip/blk_mem_rom/blk_mem_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/TheSNESRedo/TheSNESRedo.srcs/sources_1/ip/blk_mem_rom/blk_mem_rom.xci
# IP: The module: 'blk_mem_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sapph/OneDrive/Documents/GitHub/ECE385-SP24/TheSNESRedo/TheSNESRedo.gen/sources_1/ip/blk_mem_rom/blk_mem_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
