# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Spring2024Schoolwork/ECE385/ECE385-SP24-Final-Project/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam.xci
# IP: The module: 'blk_mem_gen_oam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Spring2024Schoolwork/ECE385/ECE385-SP24-Final-Project/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_oam'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Spring2024Schoolwork/ECE385/ECE385-SP24-Final-Project/SNESonUrbana/SNESonUrbana.srcs/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam.xci
# IP: The module: 'blk_mem_gen_oam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Spring2024Schoolwork/ECE385/ECE385-SP24-Final-Project/SNESonUrbana/SNESonUrbana.gen/sources_1/ip/blk_mem_gen_oam/blk_mem_gen_oam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_oam'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
